### ISSUE TITLE
add and subtract should use lcm

### ISSUE THREAD

**Issue by bk1** [ohumbel/fractions#31]
When adding or subtracting fractions, it is a good practice to create a common denominator as the least common multiple (lcm) of the denominators instead of using the product.  This helps keeping intermediate results smaller.

**Comment by ohumbel** [comment]
I fully agree here - thanks a lot for the suggestion!

**Comment by ohumbel** [comment]
I already prepared this between our discussion at Devoxx 👍 and now - I am not that fast ...

Closed via e68a812fdc9fc5da023f91177d14976fc2a0918a and 01fae55a4f80361355fa13fce51bab839bf4ac19.

**Comment by ohumbel** [comment]
Now really closed - pressing the wrong button and making typos in commit comments shades not the best light on me...

Thanks again 👍
