### ISSUE TITLE
denominator always >0

### ISSUE THREAD

**Issue by bk1** [ohumbel/fractions#32]
It is a good idea to normalize the sign in such a way that it is always carried by the numerator, while keeping the denominator > 0.

**Comment by ohumbel** [comment]
It is funny: Until a week ago, I had this in place. Then I changed it to save the (possible) two negations on construction. But thinking about `lcm` (Issue #31), it definitely makes stuff a lot easier if the denominator is always positive.

Therefore I'll partly revert commit da54cde399239ce4f279404126123944bba92c42, but keep the tests in place.

**Comment by bk1** [comment]
It makes it also easier to compare two fractions. I did not look into the equals method, but just add a test that ensures that -x/-y equals x/y (for all integral x,y with y != 0)

**Comment by ohumbel** [comment]
I'll write that test 👍

**Comment by ohumbel** [comment]
Closed via 3621b9ccbba5312582ff9551ce06f5426f556465 and c9fac834a53d83c07acc85061814e09ff7220d8e.

Thanks again.
